const dishesData = [
  {
    id: 1,
    name: '宫保鸡丁',
    category: '川菜',
    price: 42,
    description: '鸡肉滑嫩，花生酥脆，微辣开胃',
    image: '🍗',
    isSignature: true,
    isRecommend: true,
    spicy: '中辣',
  },
  {
    id: 2,
    name: '鱼香肉丝',
    category: '川菜',
    price: 38,
    description: '酸甜微辣，香气扑鼻，下饭神器',
    image: '🥩',
    isSignature: true,
    isRecommend: true,
    spicy: '微辣',
  },
  {
    id: 3,
    name: '麻婆豆腐',
    category: '川菜',
    price: 28,
    description: '麻辣鲜香，豆腐嫩滑，经典川味',
    image: '🧈',
    isSignature: true,
    isRecommend: true,
    spicy: '麻辣',
  },
  {
    id: 4,
    name: '水煮牛肉',
    category: '川菜',
    price: 58,
    description: '牛肉鲜嫩，麻辣过瘾，配菜丰富',
    image: '🥓',
    isSignature: false,
    isRecommend: true,
    spicy: '特辣',
  },
  {
    id: 5,
    name: '回锅肉',
    category: '川菜',
    price: 45,
    description: '五花肉肥而不腻，蒜苗清香',
    image: '🥩',
    isSignature: false,
    isRecommend: true,
    spicy: '微辣',
  },
  {
    id: 6,
    name: '糖醋里脊',
    category: '鲁菜',
    price: 48,
    description: '外酥里嫩，酸甜可口，色泽红亮',
    image: '🍖',
    isSignature: true,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 7,
    name: '红烧排骨',
    category: '鲁菜',
    price: 52,
    description: '肉质软烂，酱香浓郁，入口即化',
    image: '🍖',
    isSignature: true,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 8,
    name: '清蒸鲈鱼',
    category: '粤菜',
    price: 68,
    description: '鱼肉鲜嫩，原汁原味，清淡可口',
    image: '🐟',
    isSignature: true,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 9,
    name: '白灼虾',
    category: '粤菜',
    price: 88,
    description: '鲜甜Q弹，保留原味，蘸料鲜美',
    image: '🦐',
    isSignature: true,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 10,
    name: '蚝油生菜',
    category: '粤菜',
    price: 26,
    description: '生菜脆嫩，蚝油香浓，清爽解腻',
    image: '🥬',
    isSignature: false,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 11,
    name: '地三鲜',
    category: '东北菜',
    price: 32,
    description: '茄子软糯，土豆粉糯，青椒爽脆',
    image: '🥔',
    isSignature: true,
    isRecommend: true,
    spicy: '微辣',
  },
  {
    id: 12,
    name: '锅包肉',
    category: '东北菜',
    price: 46,
    description: '外酥里嫩，酸甜适口，金黄诱人',
    image: '🍖',
    isSignature: true,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 13,
    name: '拔丝地瓜',
    category: '东北菜',
    price: 28,
    description: '地瓜香甜，糖丝酥脆，趁热吃',
    image: '🍠',
    isSignature: false,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 14,
    name: '北京烤鸭',
    category: '京菜',
    price: 168,
    description: '皮脆肉嫩，荷叶饼卷食，地道京味',
    image: '🦆',
    isSignature: true,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 15,
    name: '葱爆羊肉',
    category: '京菜',
    price: 58,
    description: '羊肉鲜嫩，葱香浓郁，无膻味',
    image: '🐑',
    isSignature: false,
    isRecommend: true,
    spicy: '微辣',
  },
  {
    id: 16,
    name: '蒜蓉西兰花',
    category: '素菜',
    price: 22,
    description: '西兰花脆嫩，蒜香扑鼻，营养健康',
    image: '🥦',
    isSignature: false,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 17,
    name: '炒时蔬',
    category: '素菜',
    price: 18,
    description: '当季蔬菜，清炒鲜香，清爽可口',
    image: '🥗',
    isSignature: false,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 18,
    name: '蛋炒饭',
    category: '主食',
    price: 16,
    description: '米饭粒粒分明，蛋香浓郁',
    image: '🍚',
    isSignature: false,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 19,
    name: '担担面',
    category: '主食',
    price: 22,
    description: '川味经典，麻辣鲜香，面条劲道',
    image: '🍜',
    isSignature: true,
    isRecommend: true,
    spicy: '麻辣',
  },
  {
    id: 20,
    name: '酸辣汤',
    category: '汤品',
    price: 18,
    description: '酸辣开胃，食材丰富，暖身暖心',
    image: '🥣',
    isSignature: false,
    isRecommend: true,
    spicy: '酸辣',
  },
  {
    id: 21,
    name: '番茄蛋汤',
    category: '汤品',
    price: 16,
    description: '番茄酸甜，鸡蛋滑嫩，家常味道',
    image: '🥚',
    isSignature: false,
    isRecommend: true,
    spicy: '不辣',
  },
  {
    id: 22,
    name: '酸菜鱼',
    category: '川菜',
    price: 62,
    description: '鱼肉鲜嫩，酸菜爽口，酸香开胃',
    image: '🐟',
    isSignature: true,
    isRecommend: true,
    spicy: '中辣',
  },
  {
    id: 23,
    name: '辣子鸡',
    category: '川菜',
    price: 48,
    description: '鸡肉酥脆，辣椒红艳，麻辣鲜香',
    image: '🍗',
    isSignature: false,
    isRecommend: true,
    spicy: '特辣',
  },
  {
    id: 24,
    name: '黑椒牛柳',
    category: '粤菜',
    price: 56,
    description: '牛柳嫩滑，黑椒香浓，微辣入味',
    image: '🥩',
    isSignature: false,
    isRecommend: true,
    spicy: '微辣',
  },
  {
    id: 25,
    name: '梅菜扣肉',
    category: '粤菜',
    price: 52,
    description: '五花肉软糯，梅菜香浓，肥而不腻',
    image: '🍖',
    isSignature: true,
    isRecommend: true,
    spicy: '不辣',
  },
]

export default dishesData
